### ISSUE TITLE
Implicit dependency on {htmlwidgets}

### ISSUE THREAD

**Issue by ellisp** [timelyportfolio/d3treeR#11]
renderD3tree() depends on htmlwidgets::shinyRenderWidget() without specifying where it is, but {htmlwidgets} is only imported not loaded fully, so renderD3tree will only work in a Shiny app with {htmlwidgets} loaded explicitly.

**Comment by timelyportfolio** [comment]
@ellisp, thanks so much for this.  Sorry I forgot to fix.  I think I will also explore making this change in htmlwidgets `scaffoldWidget`.
