### ISSUE TITLE
renderD3tree not giving correct opening view for multilevel d3tree2 objects

### ISSUE THREAD

**Issue by ellisp** [timelyportfolio/d3treeR#13]
You might know all about this already.  When you print the object tmd3, as created in the code at the bottom of this comment, straight from the R console it correctly renders in the browser like this:

![image](https://cloud.githubusercontent.com/assets/5740570/8892415/c96df9ba-33a9-11e5-9617-0f2a937304e6.png)

When it's rendered in a Shiny app, it looks like this:
![image](https://cloud.githubusercontent.com/assets/5740570/8892409/aee9c632-33a9-11e5-8254-a8e47b932cf8.png)
It's trying to show all the levels at once, not just the top level of the hierarchy.

```R
library(shiny)
library(treemap)
library(d3treeR)
library(htmlwidgets) # see https://github.com/timelyportfolio/d3treeR/issues/11

Var1 <- letters[1:5]
Var2 <- LETTERS[1:5]
Var3 <- c("Tiger", "Lion", "Bear", "Penguin", "Eagle", "Aardvark")

ThreeLevels <- expand.grid(Var1, Var2, Var3)
n <- nrow(ThreeLevels)
ThreeLevels$Size <- abs(rnorm(n, 12, 3))
ThreeLevels$Colour <- rnorm(n, 0, 1)

tm <- treemap(ThreeLevels, index = c("Var1", "Var2", "Var3"), 
            vSize = "Size", vColor = "Colour",
            type = "value", palette = "Spectral",
            fun.aggregate="weighted.mean")

tmd3 <- d3tree2(tm)            


shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(p("Hello world")),
      mainPanel(d3treeOutput("tree"))
    )
  ), 
  server = function(input, output) {
    output$tree <- renderD3tree(tmd3)
   }
)

```

**Comment by timelyportfolio** [comment]
Well, if I continue to have `d3tree` and `d3tree2` then I will need to also add separate `Shiny` render functions for `d3tree2`.  I'm not crazy about having both the `Shiny`/non-`Shiny` versions, but I have not yet thought of a better way.

**Comment by timelyportfolio** [comment]
See https://github.com/timelyportfolio/d3treeR/commit/c0e312c1f730aaf8cbe568dc0fc2ae675abead50 for a temporary solution.

**Comment by timelyportfolio** [comment]
@ellisp, going to close for now.  Let me  know if you would like to reopen.

**Comment by ellisp** [comment]
works fine for now, thanks
