### ISSUE TITLE
FR: interactive legend with confidence interval support?

### ISSUE THREAD

**Issue by ignacio82** [timelyportfolio/d3treeR#14]
I'm not sure if this is possible, but it would be really useful. Whenever you have a point estimate you also have a confidence interval that might be wide or tight. Visualizing that confidence interval is very important

Consider the following example:

    library(treemap)
    library(d3treeR)
    
    data(business)
    business$employees.growth <- business$employees - business$employees.prev
    
    tm <- # Brewer's Red-White-Grey palette reversed with predefined range
      treemap(business,
              index=c("NACE1", "NACE2"),
              vSize="employees",
              vColor="employees.growth",
              type="value",
              palette="-RdGy",
              range=c(-30000,30000))
    
    d3tree2( tm, rootname = "World" )

It would be great if when hovering over a rectangle 3 triangles and with 3 numbers appear in the legend. The numbers would be the point estimate and the bounds of the confidence interval.

Doable? Thanks!

**Comment by timelyportfolio** [comment]
That would be great (related #3), but to accomplish I need to spend some time finding a way to pass the exact scale from `treemap` through to the `htmlwidget`.  It is possible, but will require some handiwork.  I'll definitely take another look.

**Comment by ignacio82** [comment]
Thanks! In case someone is looking for an example:

    library(treemap)
    library(d3treeR)
    
    data(business)
    business$employees.growth <-
      business$employees - business$employees.prev
    business$employees.se <-
      abs(business$employees.growth / business$employees.prev) * 1000
    
    
    # More control over the color palette can be achieved with mapping
    tm <- treemap(business,
            index=c("NACE1", "NACE2"),
            vSize="employees",
            stdErr="employees.se",
            vColor="employees.growth",
            type="value",
            palette="RdYlGn",
            range=c(-20000,30000),           # this is shown in the legend
            mapping=c(-30000, 10000, 40000)) # Rd is mapped to -30k, Yl to 10k, and Gn to 40k
    
    d3tree3( tm, rootname = "Root Name")

![Imgur](http://i.imgur.com/T6sjVjg.png?1)

**Comment by timelyportfolio** [comment]
Thanks @ignacio82.  Should reference pull #20
