### ISSUE TITLE
save treemap as RDS and then plot in RMD?

### ISSUE THREAD

**Issue by ignacio82** [timelyportfolio/d3treeR#16]
Is it possible to generate a treemap as an RDS file and then load it and plot it in an r markdown?

**Comment by timelyportfolio** [comment]
Yes, definitely possible, and I just confirmed using a modified version of #17. The trick in `rmarkdown` is supplying the correct path to the file.  I usually find it best to supply the full absolute path.

**Comment by ignacio82** [comment]
Not working for me... This is my code:

    ---
    title: "test"
    author: "Ignacio"
    date: "9/24/2015"
    output: html_document
    ---
    
    ## Original
    
    ```{r, echo=FALSE, warning=FALSE, fig.keep='none'}
    library(treemap)
    library(d3treeR)
    
    tree <- readRDS('tree.RDS')
    
    tree
    ```
    
And this is what I get:

![Imgur](http://i.imgur.com/swreXM0.png)

**Comment by timelyportfolio** [comment]
Sorry I misunderstood and thought your were trying to save the `treemap` as `RDS`.  The trick here is to add `library(htmlwidgets)`.  For all the gory details, see these [lines](https://github.com/ramnathv/htmlwidgets/blob/5a2725863f8bdcf74847f827dfe8a536bc699250/R/knitr-methods.R#L22-L34) from the `htmlwidgets` code.

Let me know if this works for you.

**Comment by ignacio82** [comment]
Thanks!
