### ISSUE TITLE
white space in R markdown

### ISSUE THREAD

**Issue by ignacio82** [timelyportfolio/d3treeR#17]
For example:

    ---
    title: "test"
    author: "Ignacio"
    date: "9/23/2015"
    output: html_document
    ---
    
    ## Original
    
    ```{r, echo=FALSE, warning=FALSE}
    library(treemap)
    library(d3treeR)
    
    data(business)
    business$employees.growth <-
      business$employees - business$employees.prev
    
    tm <- 
      treemap(
        business,
        index = c("NACE1", "NACE2"),
        vSize = "employees",
        vColor = "employees.growth",
        type = "value",
        palette = "RdYlGn",
        range = c(-30000,30000), 
        fun.aggregate = "weighted.mean", 
        draw = F
      )
    
    tree <- d3tree2(tm, rootname = "World")
    
    tree
    ```

Produces:

![Imgur](http://i.imgur.com/2kRSkk9.png)

**Comment by timelyportfolio** [comment]
Strange, but it appears even though you have `draw=F`, a blank `img` is getting drawn.  If possible, can you ````{r, echo=FALSE, warning=FALSE, fig.keep='none'}` to suppress this blank image.

**Comment by ignacio82** [comment]
adding `fig.keep='none'` did the trick. I had to remove `draw=F` in order to get the legend.

Thanks!
