### ISSUE TITLE
restrict number of levels and go back up without traversing to bottom first

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/d3treeR#2]
@ignacio82, good questions and in this first iteration the answer for both is "no".  However, accomplishing these is not all that difficult. See http://bost.ocks.org/mike/treemap/ for a very good treemap implementation.  I actually prefer the click on parent as a way to zoom out.  I find the gVis right + click less intuitive, but I'm sure that is a personal opinion.

I did not anticipate 10-layers deep hierarchies.  It might be helpful to understand the use case here.

I'll think through how best to accomplish both a full view and a restricted-level view.

Thanks for the feedback.

**Comment by ignacio82** [comment]
This case with 6 levels is more or less what I'm trying to do

1 School District -> 20 Schools -> 3 Grades -> many Teachers -> 4 Classroom -> many Students

This is what it looks like when you have so many levels

![tree](https://cloud.githubusercontent.com/assets/1833309/8768556/04b47758-2e53-11e5-9856-33914047a0a7.png)

**Comment by timelyportfolio** [comment]
That definitely helps.  The problem is the labelling.  In this case, I think the Mike Bostock version works much better.  I'm trying to think through I can provide access to both while minimizing function and parameter bloat.  I'll try to work through it and will enjoy your input.

**Comment by timelyportfolio** [comment]
@ignacio82 I spent a couple of hours implementing the [example from Mike Bostock](http://bost.ocks.org/mike/treemap/) and the [fork by Zan Armstrong](http://bl.ocks.org/zanarmstrong/76d263bd36f312cb0f9f).  I think it will work much better with your example.  Actually, thinking I might just go with this version instead.  Would you try it?

```
devtools::install_github("timelyportfolio/d3treeR@experiment/bostock")
```

Most everything on the R side should stay about the same.

Thanks.

**Comment by ignacio82** [comment]
@timelyportfolio great step in the right direction. The one big thing missing are the colors. This is what I get:

![tree](https://cloud.githubusercontent.com/assets/1833309/8786410/f6efd244-2efb-11e5-823d-ef8f0d4c966f.png)

and this is what I get with googleVis:

![untitled](https://cloud.githubusercontent.com/assets/1833309/8786442/1d893bac-2efc-11e5-9e94-22b9eea68adc.png)

Thanks!

**Comment by timelyportfolio** [comment]
Are you using the `treemap` package?  `d3treeR` is designed to leverage the multitude of color options provided within that package.  Do the colors on hover/mouseover appear more correct?

![image](https://cloud.githubusercontent.com/assets/837910/8787028/3e548a4e-2ef7-11e5-95e4-19525f32b065.png)


If you are using the `treemap` package, can you get a `treemap` that looks like the one with `googleVis`?

**Comment by ignacio82** [comment]
I was able to get the colors like I want.Two more questions. Is it possible to add a legend for the color like in googleVis? is it possible to personalize what the tooltip is going to show?
Thanks

**Comment by timelyportfolio** [comment]
Legends are very important, and I'm wondering how best to accomplish them, since `treemap` returns a `range` but not the full `scale`, so I'll need to recreate in `d3.js`.

I do plan to have customizable tooltips also using one of the libraries such as `d3-tip` or `kodama`.

**Comment by timelyportfolio** [comment]
also, see https://github.com/mtennekes/treemap/issues/18

**Comment by ignacio82** [comment]
Thanks for the great work!

**Comment by timelyportfolio** [comment]
Another option would be to rip the legend off from `treemap` with `gridSVG`.  Almost thinking this will  be the quickest way to get something up and going, but that will mean I will not have an immediate solution for `JSON` data.

**Comment by timelyportfolio** [comment]
@ignacio82 see https://github.com/mtennekes/treemap/issues/18 for a new `fun.aggregate` argument in `treemap` that should achieve the coloring you expect.  Please let me know how it works.

thanks again for working through this with me.

**Comment by ignacio82** [comment]
Do I need to install the dev version? I cannot make it work... `devtools::install_github('mtennekes/treemap')`  gives me `Error: Does not appear to be an R package (no DESCRIPTION)`. Sorry for the very basic question :(

**Comment by ignacio82** [comment]
@timelyportfolio thanks! `fun.aggregate` solves the problem!

**Comment by timelyportfolio** [comment]
I'll close this for now, since it is partially resolved.  I think the other standalone issues will pick up the remaining pieces.  Thanks so much @ignacio82.
