### ISSUE TITLE
Shiny reactivity of data source for treemap causes multiple treemaps to appear 

### ISSUE THREAD

**Issue by Stephen-McDaniel** [timelyportfolio/d3treeR#22]
Please run this shiny app to see the problem. Simply change the input and new treemaps will appear, a new one for every update.

Best regards,
Stephen

```
# As you modify the rows of data being used from GNI (reactivity), 
# multiple objects appear on the web page, one treemap per update

library(d3treeR)
library(treemap)

server <- function(input, output) {

   # example 1 from ?treemap
   data(GNI2010)

   GNIR <- reactive({ GNI2010[1:input$rows, ] })
   
   output$tree1 <- renderD3tree3({

      tm <- treemap(GNIR()
           ,index=c("continent", "iso3")
           ,vSize="population"
           ,vColor="GNI"
           ,type="value"
      )
      
      d3tree3(tm, rootname = "World")
      
   })

}

ui <- fluidPage(
   numericInput("rows", "Rows from GNI?", 20, min = 5, max = 208),
   d3tree3Output('tree1', height = "600px")
)

shinyApp(ui = ui, server = server)
```

**Comment by Stephen-McDaniel** [comment]
<img width="633" alt="multipletreemaps" src="https://cloud.githubusercontent.com/assets/9154079/11959453/3c1b0a50-a882-11e5-8191-6e9953d244ac.PNG">

**Comment by timelyportfolio** [comment]
Thanks for the report.  The fix should be easy, but I am away from my computer this week.  This was a contributed version, and I guess my code review was not thorough enough.  Sorry for the trouble.

**Comment by Stephen-McDaniel** [comment]
Glad to hear it should be a straightforward fix. Excellent package BTW. 

Looking forward to fix. Cheers!

Much appreciated,
Stephen
