### ISSUE TITLE
Question on the color behavior of elements

### ISSUE THREAD

**Issue by Tutuchan** [timelyportfolio/d3treeR#23]
Hi and thanks for the package,

I noticed a discrepancy in the colors of the rectangles, depending on the fact that it has children or not. Or maybe this is intended.

```r
d3treeR::d3tree3('{
  "name": "flare",
  "color": "red",
  "children": [
    {
      "name": "analytics",
      "color": "blue",
      "children": [
        {
          "name": "cluster",
          "color": "green",
          "children": [
            {"name": "AgglomerativeCluster", "size": 3938, "color": "yellow"},
            {"name": "CommunityStructure", "size": 3812, "color": "yellow"},
            {"name": "HierarchicalCluster", "size": 6714, "color": "yellow"},
            {"name": "MergeEdge", "size": 743, "color": "yellow"}
            ]
        },
        {
          "name": "graph",
          "color": "green",
          "children": [
            {"name": "BetweennessCentrality", "size": 3534, "color": "yellow"},
            {"name": "LinkDistance", "size": 5731, "color": "yellow"},
            {"name": "MaxFlowMinCut", "size": 7840, "color": "yellow"},
            {"name": "ShortestPaths", "size": 5914, "color": "yellow"},
            {"name": "SpanningTree", "size": 3416, "color": "yellow"}
            ]
        },
        {
          "name": "optimization",
          "color": "green",
          "children": [
            {"name": "AspectRatioBanker", "size": 7074, "color": "yellow"}
            ]
        }
        ]
    },
    {
      "name": "animate",
      "color": "blue",
      "children": [
        {"name": "Easing", "size": 17010, "color": "green"},
        {"name": "FunctionSequence", "size": 5842, "color": "green"},
        {
          "name": "interpolate",
          "color": "green",
          "children": [
            {"name": "ArrayInterpolator", "size": 1983, "color": "yellow"},
            {"name": "ColorInterpolator", "size": 2047, "color": "yellow"},
            {"name": "DateInterpolator", "size": 1375, "color": "yellow"},
            {"name": "Interpolator", "size": 8746, "color": "yellow"},
            {"name": "MatrixInterpolator", "size": 2202, "color": "yellow"},
            {"name": "NumberInterpolator", "size": 1382, "color": "yellow"},
            {"name": "ObjectInterpolator", "size": 1629, "color": "yellow"},
            {"name": "PointInterpolator", "size": 1675, "color": "yellow"},
            {"name": "RectangleInterpolator", "size": 2042, "color": "yellow"}
            ]
        },
        {"name": "ISchedulable", "size": 1041, "color": "green"},
        {"name": "Parallel", "size": 5176, "color": "green"},
        {"name": "Pause", "size": 449, "color": "green"},
        {"name": "Scheduler", "size": 5593, "color": "green"},
        {"name": "Sequence", "size": 5534, "color": "green"},
        {"name": "Transition", "size": 9201, "color": "green"},
        {"name": "Transitioner", "size": 19975, "color": "green"},
        {"name": "TransitionEvent", "size": 1116, "color": "green"},
        {"name": "Tween", "size": 6006, "color": "green"}
        ]
    }
    ]
}', celltext = "name")
```

Here I have a structure with 4 levels: first level is red, second level is blue, third level is green and fourth level is yellow.

When drawing the treemap, I can see that the top ribbon is indeed red but the two rectangles corresponding to the two elements at level 2 are green instead of blue. When I select the `animate` element, the top ribbon turns blue, all rectangles that dont have children are green as I would expect but there is one element that is yellow, the one with children.

My question is then: is this expected to allow differentiation at the current level between elements that have children and elements that don't ?

Thank you

EDIT: I just noticed that the estimation of the best color fails in this case because it estimates the best color for the color of the current level, not the level of the children, you can see it by clicking on `analytics` where white on yellow is hard to read. But selecting one of these elements drills down to the next level where the best color is correctly estimated as black.

**Comment by timelyportfolio** [comment]
@Tutuchan so glad you are using `d3treeR`. This is the expected behavior in `d3tree3` as far as I understand, but the author @lmccusker of this particular function could confirm.  `d3tree2` is slightly different in how it handles the colors, so the children colors only show on hover.

**Comment by Tutuchan** [comment]
Oh my bad, I didn't actually check `d3tree2`, I think this is better suited to my purposes, thanks a lot !

**Comment by timelyportfolio** [comment]
No problem at all.  These things still need quite a bit of iteration.  Also, I'd like to explore the up-and-coming d3 v4.0.0 treemap options http://bl.ocks.org/timelyportfolio/65458b68265fd35d2f68.  Please let me know if you have ideas, use cases, feedback.
