### ISSUE TITLE
Can't install d3TreeR

### ISSUE THREAD

**Issue by Dmitriy2014** [timelyportfolio/d3treeR#26]
I tried to install d3TreeR several times

`devtools::install_github("timelyportfolio/d3treeR")`

But also get an error

>     Downloading GitHub repo timelyportfolio/d3treeR@master
>     from URL https://api.github.com/repos/timelyportfolio/d3treeR/zipball/master
>     Installing d3treeR
>     "C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>       "C:/Users/user/AppData/Local/Temp/RtmpwhPDEA/devtools1b6453806f/timelyportfolio-d3treeR-28c32e0"  \
>       --library="C:/Users/user/Documents/R/win-library/3.3" --install-tests 

>     * installing *source* package 'd3treeR' ...
>     ** R
>     ** inst
>     ** preparing package for lazy loading
>     Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>     there is no package called 'influenceR'
>     ERROR: lazy loading failed for package 'd3treeR'  
>     * removing 'C:/Users/user/Documents/R/win-library/3.3/d3treeR'
>     Error: Command failed (1)

**Comment by timelyportfolio** [comment]
influenceR is not a direct dependency, but try install.packages('influencer') first to see if that fixes the problem.  Let me know.

**Comment by Dmitriy2014** [comment]
The problem fixed.
Thanks a lot!
