### ISSUE TITLE
Not rendering in Shiny

### ISSUE THREAD

**Issue by rahulanand71** [timelyportfolio/d3treeR#27]
Hi - I am a newbie to Shiny and I am trying to use the d3TreeR HTML Widget
Sample Data:
[Trader Dashboard Data Prep Sample.xlsx](https://github.com/timelyportfolio/d3treeR/files/641627/Trader.Dashboard.Data.Prep.Sample.xlsx)

I used the following code and it ran perfectly in R:
```

    library(readxl)
    budget_map <- read_excel(path = 'Trader Dashboard Data Prep Sample.xlsx',sheet='v2',col_names = TRUE)
    library(treemap)
    budget_treemap <- treemap(budget_map,index=c("Sales Agency","Agency","Advertiser"),vSize="Booked Revenue Net",vColor="Sales Agency",palette = "Set1",type="categorical",title="Australia Budget Map",fontsize.title=22)
    library(d3treeR)
    d3tree2(budget_treemap)

```
I'm trying to get it to render in Shiny and am using the following code:

```
    library(shiny)
    library(readxl)
    library(treemap)
    library(htmlwidgets)
    library(data.tree)
    library(d3treeR)
    budget_map <- read_excel(path = 'C:/Users/rahul/Desktop/30k foot view/Trader Dashboard Data Prep Sample.xlsx',sheet='v2',col_names = TRUE)
    budget_treemap <- treemap(budget_map,index=c("Sales Agency","Agency","Advertiser"),vSize="Booked Revenue Net",vColor="Sales Agency",palette = "Set1",type="categorical")
    
    ui <- fluidPage(
      d3tree2Output("au_budget_map")
    )
    

    
    
    server <- function(input,output){
        output$au_budget_map <- renderD3tree2({budget_treemap})
    }
    
    shinyApp(ui = ui, server = server)
```
Not sure why it isnt rendering - any help will be greatly appreciated!

**Comment by rahulanand71** [comment]
My bad - figured that the input for the renderD3tree2 would have to be d3tree2 so, the code should have been:

output$au_budget_map <- renderD3tree2({d3tree2(budget_treemap)})

**Comment by timelyportfolio** [comment]
No problem.  Glad you are using.  Should probably add S3 for treemap.

**Comment by rahulanand71** [comment]
Thank You for responding!
P.S: Sorry but didnt get that bit  - as in, the bit on adding S3 for treemap?
