### ISSUE TITLE
height and width setting in d3tree or d3tree2 not working in shiny

### ISSUE THREAD

**Issue by ningzhibin** [timelyportfolio/d3treeR#31]
Not sure if I am doing it in the wrong way or a bug
the height and width setting in d3tree or d3tree2 does not work in shiny, but works in Rstudio
This is the code in Rstudio:
 ##########################
data(business)
business$employees.growth <- business$employees - business$employees.prev
    d3tree2(treemap(business,
                    index=c("NACE1", "NACE2"),
                    vSize="employees",
                    vColor="employees.growth",
                    type="value",
                    palette="-RdGy",
                    range=c(-30000,30000)),
    rootname = "Fictitious Business Data" ,
    height = "1200px",
    width = "50%")

#########################
This is the code for shiny:
########################
library(shiny)
library(treemap)
library(d3treeR)

ui <- fluidPage(
   
   titlePanel("Treemap not sizable?"),
   d3tree2Output('tree')
     
)

server <- function(input, output) {
  data(business)
  business$employees.growth <- business$employees - business$employees.prev
  output$tree <- renderD3tree2({

    d3tree2(treemap(business,
                    index=c("NACE1", "NACE2"),
                    vSize="employees",
                    vColor="employees.growth",
                    type="value",
                    palette="-RdGy",
                    range=c(-30000,30000)),
    rootname = "Fictitious Business Data" ,
    height = "1200px",
    width = "50%")
    
  })
}
shinyApp(ui = ui, server = server)

**Comment by ningzhibin** [comment]
figured out, my bad
height = 1200

**Comment by timelyportfolio** [comment]
Ok, sorry I was not able to respond quickly.  Just in case someone runs into the same problem with this or other `htmlwidgets`, I will write a little more thorough answer.

To control height/width with an `htmlwidget` in Shiny, the output function (in this case `d3tree2Output`) is used rather than the htmlwidget creation function.  In the UI part of the app,

```
ui <- fluidPage(

titlePanel("Treemap now sizable"),
d3tree2Output('tree', height=1200)
```

...and in the server piece

```
server <- function(input, output) {
data(business)
business$employees.growth <- business$employees - business$employees.prev
output$tree <- renderD3tree2({

d3tree2(treemap(business,
                index=c("NACE1", "NACE2"),
                vSize="employees",
                vColor="employees.growth",
                type="value",
                palette="-RdGy",
                range=c(-30000,30000)),
rootname = "Fictitious Business Data" 
))
})

}
```

Hope this helps.
