### ISSUE TITLE
cant install the library

### ISSUE THREAD

**Issue by volha-tryputsen** [timelyportfolio/d3treeR#32]
Hello,
I have an installation issue after running install_github("timelyportfolio/d3treeR"). See the error message below: 
_Error: package or namespace load failed for ‘d3treeR’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/dplyr/R/dplyr.rdb' is corrupt In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1_

Thanks,
Volha

**Comment by timelyportfolio** [comment]
usually, restarting your R session will fix this problem.  Let me know if it doesn't.  Thanks for using.  I have not updated in a while since I have not seen much interest lately.

**Comment by volha-tryputsen** [comment]
thanks, that worked!

**Comment by timelyportfolio** [comment]
Hope everything went well as you used `d3treeR`.  Please let me know if the experience was not good or you would like to see more features.  Going to close this, since it seems the issue has been resolved.
