### ISSUE TITLE
Treemap as input for reactive variable/function?

### ISSUE THREAD

**Issue by jxg852** [timelyportfolio/d3treeR#34]
Can the treemap be used as an input for a reactive variable or function - i.e. a table that filters based on the area of the treemap you click into?

**Comment by timelyportfolio** [comment]
See if https://github.com/timelyportfolio/d3treeR/issues/11 helps.

**Comment by jxg852** [comment]
Would you be able to provide a bit more context? I don't really know much about html so can't really tell if/how #11 would help my issue. Thanks in advance.

**Comment by timelyportfolio** [comment]
Might be best for you to explain what you are trying to do with some reproducible code.

**Comment by timelyportfolio** [comment]
closing due to lack of response.  please reopen if you would like to discuss further.
