### ISSUE TITLE
Interactive treemaps in loop (d3treeR)

### ISSUE THREAD

**Issue by patcrao** [timelyportfolio/d3treeR#35]
Hello. 
I want to make interactive treemaps in R markdown. That is, produce one html file which contains several treemaps. My problem is : when i do one treemap, it is ok. When i make one loop with several treemaps for several analysis, it produces nothing.

Does anyone have any solution?

Thank you very much.

**Comment by timelyportfolio** [comment]
I am guessing enclosing in `htmltools::tagList()` will solve your problem.

```
library(htmltools)
library(d3treeR)

tagList(
  lapply(
    ... your list ...,
    function(x) {
      d3treeR(x, ...)
    }
  )
)
```

If not, please provide some reproducible code.

**Comment by patcrao** [comment]
Hello.
I tried with these instructions. It seems to be working. The treemaps remain interactive even if you repeat. Moreover, i solved another problem i had: there was a big white space just above the interactive treemap. I divided my code into two differents chunks. and i made it.
For now, it is working! I thank you very much!

**Comment by timelyportfolio** [comment]
Glad to hear; going to close, but feel free to reopen.
