### ISSUE TITLE
New Line in Group Name

### ISSUE THREAD

**Issue by yerocyt** [timelyportfolio/d3treeR#42]
Hi,

Less of an issue more a question of possibility.

I would like the final group to contain a couple of lines of information..
e.g. 
customer: John Smith
telephone: 071234567

I'm struggling to add a new line, apologies if this is a simple question, I am rather new to the space

**Comment by Guillamon** [comment]
Hi yerocyt,
Did you find a solution for this?

**Comment by agricolamz** [comment]
Anyone?
