### ISSUE TITLE
dependency issue: data.table 1.9.5 makes treemap fall over 

### ISSUE THREAD

**Issue by markriseley** [timelyportfolio/d3treeR#7]
Not a bug for your package, but treemap falls over with data.table 1.9.5

See https://github.com/Rdatatable/data.table/issues/1216

**Comment by markriseley** [comment]
I think I fixed it on the treemap side with this pending pull request (changed 2 lines in treemap)

https://github.com/mtennekes/treemap/pull/19

**Comment by timelyportfolio** [comment]
Thanks so much for spotting and pulling.  Guess we can close for now.  Let me know if we need to reopen.
