### ISSUE TITLE
calculate color for higher level rectangles from weighted average of lower level when type='value'

### ISSUE THREAD

**Issue by ellisp** [timelyportfolio/d3treeR#8]
Consider the example below, converting a {treemap} object for use by d3tree2.  When you click down to the level where the value that has been given to vColor exists, Borduria looks like this:

![image](https://cloud.githubusercontent.com/assets/5740570/8888335/9d085eee-32fd-11e5-9889-60276686748b.png)

The average value/color intuitively should be 2.6, hence a pale yellow/green, but instead we get purple/10, more or less aribtrarily (I'm not sure exactly why, but could imagine reasons).

![image](https://cloud.githubusercontent.com/assets/5740570/8888341/bbfb7ebc-32fd-11e5-9e6b-5e0c85a5e6c1.png)

It would be very useful if in this case the color assigned to the higher level rectangles was a weighted average of the values assigned to color the level below, until you reach the rectangles that have values actually assigned from originally.  (I might have a crack at this myself down the track, but not in the immediate next few weeks.)

```R
library(treemap)
library(d3treeR)
library(dplyr)

mock <- data.frame(
   Country = rep(c("Ruritania", "Borduria"), 3),
   Industry = rep(c("Accommodation", "Manufacturing", "Flower growing"), each = 2),
   GDP = c(1000, 500, 20, 2000, 1800, 70), 
   Growth = c(-5, 4, -3, 2, -7, 10)
   )
   
tm <- treemap(mock, index = c("Country", "Industry"), vSize = "GDP", vColor = "Growth", 
               type = "value", palette = "Spectral")
d3tree2(tm, rootname = "World")

# what should the country colours be? Probably mean vColor value, weighted by vSize:
mock %>%
   group_by(Country) %>%
   summarise(AvGrowth = round(sum(GDP * Growth) / sum(GDP), 1))

```

**Comment by ignacio82** [comment]
Try adding `fun.aggregate`:

    tm <- treemap(mock, index = c("Country", "Industry"), vSize = "GDP", vColor = "Growth", 
                  type = "value", palette = "Spectral", 
                  fun.aggregate="weighted.mean")
    d3tree2(tm, rootname = "World")

**Comment by timelyportfolio** [comment]
Thanks @ignacio82.  @ellisp treemap was not originally designed for this since colors only appear at the lowest level.  Fortunately @mtennekes quickly added in https://github.com/mtennekes/treemap/issues/18.  Would love feedback.

**Comment by ellisp** [comment]
Perfect, exactly what I was looking for, thanks all.
