### ISSUE TITLE
FR: communicating click events; or generalisable click functions?

### ISSUE THREAD

**Issue by ellisp** [timelyportfolio/d3treeR#9]
It would be useful to have some way of storing / communicating the result of a click on one of the rectangles, so as well as impacting on the d3 visualisation it could be used to modify other content of a Shiny app or web page.  The aim being to make it easier to create this sort of functionality: http://www.mbie.govt.nz/what-we-do/business-growth-agenda/regions/web-tool-desktop#employee-count/retail-trade/christchurch from within the R/Shiny environment rather than hand coding JavaScript (which is what we did in that case).

Similar to this in networkD3 https://github.com/christophergandrud/networkD3/pull/59 , which lets the user specify a JavaScript function to execute on click, which can then pass information on the clicked node to Shiny via Shiny.onInputChange() .

**Comment by timelyportfolio** [comment]
in 1f37d1d, I start to add the `Shiny` integration, by returning the `celltext`/likely name of the clicked cell.  Here is a basic example.

```
library(shiny)
library(treemap)
library(d3treeR)

data(business)
tm <- treemap(business,
              index=c("NACE1", "NACE2","NACE3"),
              vSize="employees",
              fontsize.labels=12,
              lowerbound.cex.labels=1, draw = F)

ui <- list(
  d3tree2Output( 'tree' )
  ,textOutput( "clickedinfo", container = p )
)

server <- function( input, output, session ){
  output$tree <- renderD3tree2({
    d3tree2( tm )
  })
  
  # from https://github.com/rstudio/leaflet/blob/master/inst/examples/shiny.R
  v <- reactiveValues(msg = "")
  
  observeEvent(input$tree_click, {
    v$msg <- paste("Clicked ", input$tree_click$name)
  })
  
  output$clickedinfo <- renderText(v$msg)
}

shinyApp( ui, server )
```

I'll start experimenting with the second part of the request which is a generalizable click handler that could trigger actions on the JavaScript side.

**Comment by timelyportfolio** [comment]
@ellisp ad0d8b0 should provide a first implementation of `clickAction` for `d3tree2`.  I opted for what I considered the easier but much more limited form of the implementation.  If I can broaden my assumption that someone providing `clickAction` understands JavaScript `call`/`this`, then I could use the more powerful form where I `call` the `clickAction` with `d` which is all the node info, `g` which is the SVG element, and `el` which is the htmlwidget element.  In this case `function(){return this}` would give us an object `{d:...,g:...,el:...}`

**Comment by ellisp** [comment]
brilliant, I'll have a look some time this week

**Comment by ellisp** [comment]
This is great and gets me most of the way where I was hoping, except that when you get to the end of the hierarchy and click on one of the twigs of the tree it doesn't register.  It doesn't need to for treemap-drawing purposes as it's already got the most granular graphic up there, but it would be good to have that final twig known to the app when it's clicked on.

**Comment by timelyportfolio** [comment]
Oh I missed that. I should be able to push that out tonight.  Thanks.

**Comment by timelyportfolio** [comment]
I think I got it right in 3f300771e968d0815d9ae46b315656acf60913c9.  The examples provided above now communicate click/selection on the top grandparent level (title bar), parent level, and at the cell level including the leaves.  If possible, please test on your end.

Thanks again.

**Comment by ellisp** [comment]
Tested at my end and it does the job, thanks.
